[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "MicroGridsPy Documentation"
authors = [{name = "Alessandro Onori", email = "alessandro.onori@polimi.it"}]
dynamic = ["version", "description"]
